### PR TITLE
NO-ISSUE: openapiconfig: generate base config using DefaultOpenAPIConfig

### PR DESCRIPTION
**Pull request by liouk**
This PR addresses this comment: https://github.com/openshift/oauth-apiserver/pull/108#discussion_r1560827754

/assign @p0lyn0mial

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
thanks!

/lgtm
/assign @stlaz 

for approval.

**Comment by liouk** [comment]
/retitle NO ISSUE: openapiconfig: generate base config using DefaultOpenAPIConfig

**Comment by liouk** [comment]
/retitle NO-ISSUE: openapiconfig: generate base config using DefaultOpenAPIConfig

**Pull request merged**
