### PR TITLE
OCPBUGS-27094: UPSTREAM: <carry>: retry etcd Unavailable errors

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
/hold

it's a proof pr, once everything is great, we can merge https://github.com/openshift/kubernetes-apiserver/pull/51 and bring this in

**Comment by p0lyn0mial** [comment]
a proof pr for https://github.com/openshift/kubernetes-apiserver/pull/52 

#51 was for `oas`

**Comment by p0lyn0mial** [comment]
LGTM, thanks!

**Comment by tkashem** [comment]
assign @stlaz @deads2k

**Pull request merged**
