### PR TITLE
bump kube to 1.24.4

### PR DESCRIPTION
**Pull request by ibihim**
# What

- Bump k8s deps to 1.24.4

# Why

- To fix https://github.com/kubernetes/kubernetes/issues/109115,
- which is the root cause of https://issues.redhat.com/browse/OCPBUGS-533

### CODE REVIEW

**Comment by ibihim** [comment]
> E0908 16:43:43.583604       1 run.go:74] "command failed" err="unable to install api resources: resource names must be lowercase only, not \"userOAuthAccessTokens\""

https://github.com/kubernetes/apiserver/commit/7fd5822a0856433177a4a0dc7bb1c20ebc5cb087#diff-8a9e80dac2f71f42eec6f73ac6ed84f4475dd82e00123e592d134c9d5a43ab7cR662

**Comment by s-urbaniak** [comment]
good stuff @ibihim !!!! 👏 This was a tough one 💪

**Pull request merged**
