### PR TITLE
[release-4.10] OCPBUGS-2553: bump kube to 1.23.12 to fix group sync

### PR DESCRIPTION
**Pull request by ibihim**
# What

Create a backport of the watcher fix (#81) in k/k >1.23.5 to OpenShift 4.10.z 

# Why

Watcher was broken upstream in k/k >1.23.0-alpha till <1.23.5.

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
fails on
```
I1020 15:31:36.906958   23024 main.go:81] Completed successfully.
hack/verify-generated-openapi.sh
Generating origin openapi
2022/10/20 15:32:10 OpenAPI code generation error: Failed executing generator: some packages had errors:
errors in package "github.com/openshift/oauth-apiserver//pkg/openapi":
output for "openapi/zz_generated.openapi.go" differs; first existing/expected diff: 
  "\\n\\nPossible enum values:\\n - `\\\"Complete\\\"` means the job has completed its execution.\\n - `\\\"Faile"
  "\",\n\t\t\t\t\t\t\tDefault:     \"\",\n\t\t\t\t\t\t\tType:        []string{\"string\"},\n\t\t\t\t\t\t\tFormat:      \"\",\n\t\t\t\t\t\t},\n"

make: *** [Makefile:40: verify] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-20T15:32:10Z"} 
[36mINFO[0m[2022-10-20T15:32:25Z] Ran for 13m4s                                
[31mERRO[0m[2022-10-20T15:32:25Z] Some steps failed:                           
[31mERRO[0m[2022-10-20T15:32:25Z] 
  * could not run steps: step verify failed: test "verify" failed: the pod ci-op-spvmw492/verify failed after 2m4s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 2, reason Error
```

please regenerate OpenAPI

**Comment by ibihim** [comment]
/retitle [release-4.10] OCPBUGS-2553: bump kube to 1.23.12 to fix group sync

**Pull request merged**
