### PR TITLE
NO-JIRA: Bump 1.30

### PR DESCRIPTION
**Pull request by dinhxuanvu**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
let's merge https://github.com/openshift/openshift-apiserver/pull/441 first.

**Comment by dinhxuanvu** [comment]
@p0lyn0mial AOS PR has been merged. So we can merge this PR now.

**Comment by tkashem** [comment]
/lgtm
/approve

/hold
(in case you want other folks to review)

(i did not follow the client gen work done upstream, so i don't understand the changes in the script )

**Pull request merged**
